# Generated by Django 3.1.4 on 2020-12-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='English_19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options1', models.TextField()),
                ('options2', models.TextField()),
                ('options3', models.TextField()),
                ('options4', models.TextField()),
                ('right_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Passages_19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passages', models.TextField(blank=True)),
            ],
        ),
    ]
