# Generated by Django 3.1.4 on 2020-12-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='English_19',
            new_name='English_20119',
        ),
    ]
