# Generated by Django 3.1.4 on 2020-12-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0002_auto_20201210_1428'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='English_20119',
            new_name='English_2019',
        ),
    ]
