# Generated by Django 3.1.4 on 2020-12-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0003_auto_20201210_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eng_Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('Optional', models.TextField(blank=True)),
                ('Optiona2', models.TextField(blank=True)),
                ('Optiona3', models.TextField(blank=True)),
                ('Optiona4', models.TextField(blank=True)),
                ('correct_option', models.TextField(blank=True)),
            ],
        ),
    ]
