# Generated by Django 3.1.4 on 2020-12-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0004_eng_quest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eng_quest',
            old_name='Optiona2',
            new_name='options2',
        ),
        migrations.RenameField(
            model_name='eng_quest',
            old_name='Optiona3',
            new_name='options3',
        ),
        migrations.RenameField(
            model_name='eng_quest',
            old_name='Optiona4',
            new_name='options4',
        ),
        migrations.RenameField(
            model_name='eng_quest',
            old_name='Optional',
            new_name='optionsl',
        ),
    ]
