# Generated by Django 3.1.4 on 2020-12-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0005_auto_20201210_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eng_quest',
            old_name='question',
            new_name='quest',
        ),
    ]
