# Generated by Django 3.1.4 on 2020-12-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0006_auto_20201210_1619'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eng_Quest',
        ),
        migrations.DeleteModel(
            name='English_2019',
        ),
        migrations.DeleteModel(
            name='Passages_19',
        ),
    ]
