# Generated by Django 3.1.4 on 2020-12-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0009_auto_20201211_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='user_answer',
            field=models.TextField(default=''),
        ),
    ]
