# Generated by Django 3.1.4 on 2020-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0010_auto_20201211_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english19',
            name='option1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='english19',
            name='option2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='english19',
            name='option3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='english19',
            name='option4',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='english19',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
