# Generated by Django 3.1.4 on 2020-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0012_auto_20201211_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
