# Generated by Django 3.1.4 on 2020-12-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0016_auto_20201212_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='test',
        ),
    ]
