# Generated by Django 3.1.4 on 2020-12-14 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0019_auto_20201212_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='test',
        ),
    ]
