# Generated by Django 3.1.4 on 2020-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0021_auto_20201219_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english19',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
    ]
