# Generated by Django 3.1.4 on 2020-12-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0022_auto_20201219_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='english19',
            name='has_img',
        ),
    ]
