# Generated by Django 3.1.4 on 2020-12-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0023_remove_english19_has_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='english19',
            name='has_img',
            field=models.BooleanField(default=False),
        ),
    ]
