# Generated by Django 3.1.4 on 2020-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utme', '0025_auto_20201219_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='english19',
            name='right_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='english19',
            name='right_answer_img',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
